export const authConstants = {

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",


}

export const userConstants = {
    GET_ALL_USER_REQUEST: 'GET_ALL__USER_REQUEST',
    GET_ALL_USER_FAILURE: 'GET_ALL__USER_FAILURE',
    GET_ALL_USER_SUCCESS: 'GET_ALL__USER_SUCCESS',

    GET_APPROVE_USER_REQUEST: 'GET_APPROVE_USER_REQUEST',
    GET_APPROVE_USER_FAILURE: 'GET_APPROVE_USER_FAILURE',
    GET_APPROVE_USER_SUCCESS: 'GET_APPROVE_USER_SUCCESS',

    GET_AWAITING_APPROVE_USER_REQUEST: 'GET_AWAITING_APPROVE_USER_REQUEST',
    GET_AWAITING_APPROVE_USER_FAILURE: 'GET_AWAITING_APPROVE_USER_FAILURE',
    GET_AWAITING_APPROVE_USER_SUCCESS: 'GET_AWAITING_APPROVE_USER_SUCCESS',

    DELETE_USER_BY_ID_REQUEST: 'DELETE_USER_BY_ID_REQUEST',
    DELETE_USER_BY_ID_FAILURE: 'DELETE_USER_BY_ID_FAILURE',
    DELETE_USER_BY_ID_SUCCESS: 'DELETE_USER_BY_ID_SUCCESS',

    APPROVE_USER_BY_ID_REQUEST: 'APPROVE_USER_BY_ID_REQUEST',
    APPROVE_USER_BY_ID_FAILURE: 'APPROVE_USER_BY_ID_FAILURE',
    APPROVE_USER_BY_ID_SUCCESS: 'APPROVE_USER_BY_ID_SUCCESS',
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',

    ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',

    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',

    UPDATE_CATEGORY_REQUEST: 'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
}

export const postConstants = {
    GET_ALL_POST_REQUEST: 'GET_ALL_POST_REQUEST',
    GET_ALL_POST_FAILURE: 'GET_ALL_POST_FAILURE',
    GET_ALL_POST_SUCCESS: 'GET_ALL_POST_SUCCESS',

    GET_POST_BY_USER_REQUEST: 'GET_POST_BY_USER_REQUEST',
    GET_POST_BY_USER_FAILURE: 'GET_POST_BY_USER_FAILURE',
    GET_POST_BY_USER_SUCCESS: 'GET_POST_BY_USER_SUCCESS',

    GET_ID_POST_REQUEST: 'GET_ID_POST_REQUEST',
    GET_ID_POST_FAILURE: 'GET_ID_POST_FAILURE',
    GET_ID_POST_SUCCESS: 'GET_ID_POST_SUCCESS',

    GET_APPROVE_POST_REQUEST: 'GET_APPROVE_POST_REQUEST',
    GET_APPROVE_POST_FAILURE: 'GET_APPROVE_POST_FAILURE',
    GET_APPROVE_POST_SUCCESS: 'GET_APPROVE_POST_SUCCESS',

    GET_PENDING_APPROVE_POST_REQUEST: 'GET_PENDING_APPROVE_POST_REQUEST',
    GET_PENDING_APPROVE_POST_FAILURE: 'GET_PENDING_APPROVE_POST_FAILURE',
    GET_PENDING_APPROVE_POST_SUCCESS: 'GET_PENDING_APPROVE_POST_SUCCESS',

    ADD_POST_REQUEST: 'ADD_POST_REQUEST',
    ADD_POST_FAILURE: 'ADD_POST_FAILURE',
    ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',

    DELETE_POST_BY_ID_REQUEST: 'DELETE_POST_BY_ID_REQUEST',
    DELETE_POST_BY_ID_FAILURE: 'DELETE_POST_BY_ID_FAILURE',
    DELETE_POST_BY_ID_SUCCESS: 'DELETE_POST_BY_ID_SUCCESS',

    UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
    UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',

    UPDATE_STATUS_POST_BY_ID_REQUEST: 'UPDATE_STATUS_POST_BY_ID_REQUEST',
    UPDATE_STATUS_POST_BY_ID_FAILURE: 'UPDATE_STATUS_POST_BY_ID_FAILURE',
    UPDATE_STATUS_POST_BY_ID_SUCCESS: 'UPDATE_STATUS_POST_BY_ID_SUCCESS',

    UPDATE_APPROVE_POST_REQUEST: 'UPDATE_APPROVE_POST_REQUEST',
    UPDATE_APPROVE_POST_FAILURE: 'UPDATE_APPROVE_POST_FAILURE',
    UPDATE_APPROVE_POST_SUCCESS: 'UPDATE_APPROVE_POST_SUCCESS',

    DOAWNLOAD_POST_REQUEST: 'DOAWNLOAD_POST_REQUEST',
    DOAWNLOAD_POST_FAILURE: 'DOAWNLOAD_POST_FAILURE',
    DOAWNLOAD_POST_SUCCESS: 'DOAWNLOAD_POST_SUCCESS',
}


